### ISSUE TITLE
Touch Input inverted in Y direction on reMarkable 2

### ISSUE THREAD

**Issue by timower** [alex0809/netsurf-reMarkable#13]
Awesome work on getting netsurf on the rM!

Just something I noticed on the rM2, pen input works but touch input is inverted.

**Comment by alex0809** [comment]
Thanks @timower! Are both of the axes inverted or just one?

**Comment by timower** [comment]
Both, the screen needs to be rotated 180 degrees essentially

**Comment by alex0809** [comment]
In that case, I think the next version should fix it, with https://github.com/alex0809/libnsfb-reMarkable/commit/4ab38de644682a42169dc0229d432b319df5867d

I had inverted the wrong axis
