### ISSUE TITLE
[How to] Remarkable 2 and Framebuffer

### ISSUE THREAD

**Issue by Pemo11235** [alex0809/netsurf-reMarkable#2]
Hi,
to work on rm2 it needs the frambuffer server? to launch the app can I use draft (remux)? 
thanks for help !

**Comment by Eeems** [comment]
Yes it does need rm2fb and you can launch it with any launcher.

**Comment by alex0809** [comment]
Thanks for the confirmation @Eeems! I don't have an rm2 myself to test.

**Comment by Eeems** [comment]
@alex0809 You may want to include a draft and/or Oxide application registration file to make it easier for people to use.
https://github.com/dixonary/draft-reMarkable/#configuration-files
https://github.com/Eeems/oxide/wiki/Developing-Applications-for-Oxide#oxide-application-registration-specification
