### ISSUE TITLE
How to start netsurf on reMarkable2?

### ISSUE THREAD

**Issue by rainnus** [alex0809/netsurf-reMarkable#22]
When I run netsurf on reMarkable 2, I got this:
```
DEBUG: fb_initialize: Framebuffer /dev/fb0 opened
DEBUG: fb_initialize: Screeninfo loaded
DEBUG: fb_initialize: mmapped 24893440 bytes of framebuffer
DEBUG: rm_defaults: Screen defaults set to: width=260, height=1408, bpp=16, linelen=1040
DEBUG: rm_set_geometry: not implemented!
DEBUG: input_identify_input_devices: Device identified as RM2
DEBUG: input_identify_input_devices: Identified /dev/input/event2 as multitouch input
DEBUG: input_identify_input_devices: Identified /dev/input/event1 as pen input
DEBUG: input_identify_input_devices: Identified /dev/input/event0 as GPIO input
DEBUG: input_identify_input_devices: Identified all devices.
DEBUG: input_initialize: Multitouch device has 32 slots, x is between 0 and 1403, y is between 0 and 1871)
DEBUG: input_initialize: pen device x is between 0 and 20966, y is between 0 and 15725)
Unable to initialise the font system
```

**Comment by Eeems** [comment]
Do you have rm2fb installed?

**Comment by rainnus** [comment]
> Do you have rm2fb installed?

Yes，I have rm2fb installed. But I have no idea how to run netsurf rightly...

I try to start it by remux, but I got blank sceen.

**Comment by Eeems** [comment]
How did you install netsurf?

**Comment by alex0809** [comment]
This error sounds like missing or incomplete font configuration in the `Choices` file.

In general, I recommend installing the ipk package as it will take care of installing the fonts that are pre-configured.

If you build and install via `make install`, you have to configure the fonts yourself.

**Comment by rainnus** [comment]
> This error sounds like missing or incomplete font configuration in the `Choices` file.
> 
> In general, I recommend installing the ipk package as it will take care of installing the fonts that are pre-configured.
> 
> If you build and install via `make install`, you have to configure the fonts yourself.

This is indeed the reason. Through the modification of `Choices` file, netsurf has been successfully launched now. Thank you so much.
