### ISSUE TITLE
No @ sign on keyboard

### ISSUE THREAD

**Issue by athousandprojects** [alex0809/netsurf-reMarkable#30]
There does not appear to be an @ sign on the keyboard. This makes it impossible to login into just about any web page.

**Comment by alex0809** [comment]
The on-screen keyboard is British layout, so Shift ' corresponds to the @ sign.

I know this is quite opaque. The keyboard layout is hardcoded so it would require some coding effort to allow e.g. defining the keyboard map in the Choices file.

**Comment by athousandprojects** [comment]
ok, thanks - and yes, that's abut opaque as you can get :-)
